<a href="https://colab.research.google.com/github/DavidStrickland19/Developing-an-open-source-Library-Numerical-Analysis-/blob/main/Numerical_Analysis_Library_with_examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**FIXED POINT ITERATION**

In [16]:
#EXERCISE NUMBER 3
#Y0 = 1/2      Y1 = 0.5433216987500 are fixed and take h= .125
# y(n+1) = 1.3333333(Y1) -  .3333333(Y0) - 2h(yn)* ln(yn)
#y0 = Y1
                                
import math

f = lambda x, Y1, Y0, h: (1.3333333 * (Y1)) - ( .3333333 * (Y0)) - ( (2*h*x)) * (math.log(x))                              

Y0 = 0.5
Y1 = 0.5433216987500
h = .125
x0 = Y1
n = 10

#--------------------------------------------------------------------------------------------

def iter3(f,x,Y1,Y0,h,n):
    for i in range(n):
        x= f(x,Y1,Y0, h)
        print ('Iteration *{} is: {}'.format(i,x))
        
iter3(f,x0,Y1,Y0,h,n)



Iteration *0 is: 0.6406261150006851
Iteration *1 is: 0.6290814514472624
Iteration *2 is: 0.6306562175914519
Iteration *3 is: 0.6304445075825247
Iteration *4 is: 0.6304730269185157
Iteration *5 is: 0.6304691861305768
Iteration *6 is: 0.630469703400262
Iteration *7 is: 0.6304696337357498
Iteration *8 is: 0.630469643117988
Iteration *9 is: 0.6304696418544123


**FAMILY OF MARTRICIES**

In [11]:
import numpy
def HnMatrix(n):
    H = numpy.empty([n, n], dtype=numpy.float64)
    
    for i in range(n):
        for j in range (n):
            H[i,j] = 1.0/((i+1) + (j+1) - 1.0)
    
    return H

HnMatrix(5)
    

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667],
       [0.33333333, 0.25      , 0.2       , 0.16666667, 0.14285714],
       [0.25      , 0.2       , 0.16666667, 0.14285714, 0.125     ],
       [0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111]])

In [13]:
def KnMatrix(n):
    K = numpy.empty([n, n], dtype=numpy.float64)
    
    for i in range(n):
        for j in range (n):
            if( i == j ):
                K[i,j] = 2.0
            elif( abs(i - j ) == 1):
                K[i,j] = -1.0
            else:
                K[i,j] = 0.0
                
    return K

KnMatrix(5) 

array([[ 2., -1.,  0.,  0.,  0.],
       [-1.,  2., -1.,  0.,  0.],
       [ 0., -1.,  2., -1.,  0.],
       [ 0.,  0., -1.,  2., -1.],
       [ 0.,  0.,  0., -1.,  2.]])

In [14]:
def TnMatrix(n):
    T = numpy.full([n, n], 0.0)

    for i in range(n):
        for j in range (n):
            if( i == j ):
                T[i,j] = 4.0
            elif( abs(i - j) == 1):
                T[i,j] = 1.0
            else:
                T[i,j] = 0.0
                
    return T

TnMatrix(5) 

array([[4., 1., 0., 0., 0.],
       [1., 4., 1., 0., 0.],
       [0., 1., 4., 1., 0.],
       [0., 0., 1., 4., 1.],
       [0., 0., 0., 1., 4.]])

In [15]:
def AnMatrix(n):
    A = numpy.empty([n, n], dtype=numpy.float64)
    
    for i in range(n):
        for j in range (n):
            if( i == j ):
                A[i,j] = 1.0
            elif( i - j == 1):
                A[i,j] = 4.0
            elif( i - j == -1):
                A[i,j] = -4.0
            else:
                A[i,j] = 0.0
                
    return A

AnMatrix(5)

array([[ 1., -4.,  0.,  0.,  0.],
       [ 4.,  1., -4.,  0.,  0.],
       [ 0.,  4.,  1., -4.,  0.],
       [ 0.,  0.,  4.,  1., -4.],
       [ 0.,  0.,  0.,  4.,  1.]])

**GAUSSIAN ELIMINATION WITH PIVOTING**

In [84]:
def algorithm_74(Amatrix, bvector):
    (numrows, numcols) = Amatrix.shape
    a = Amatrix.copy()
    b = bvector.copy()
    
    #making sure that our matrix is square
    if(numrows == numcols):
        
        for i in range(numrows):
            #the elimination steps to get the upper triangular form, looking for pivots
            
            am = abs(a[i,i])
            pivot = i
        
            #looping through to make sure pivot index is the index with the largest abs value
            for j in range(i+1, numrows):
                if( abs(a[j,i]) > am):
                    am = abs(a[j,i])
                    pivot = j
                
                if( pivot > i ):
                    #execute row interchange so that the pivot is in the ith row
                    for k in range(i, numcols):
                        temp = numpy.copy(a[i,k])
                        a[i,k] = a[pivot,k]
                        a[pivot,k] = temp

                
                    hold = numpy.copy(b[i,0])
                    b[i,0] = b[pivot,0]
                    b[pivot,0] = hold
            
            for j in range(i+1, numrows):
                m = a[j,i]/a[i,i]
            
                for k in range(i+1, numrows):
                    a[j,k] = a[j,k] - m*a[i,k]
            
                b[j,0] = b[j,0] - m*b[i,0]
            
            
        #back solver part
        x = numpy.matrix(numpy.zeros((numrows,1), dtype = numpy.float64))
        n = numrows - 1
        x[n,0] = b[n,0]/a[n,n]    
        
        #going up along the diagonal
        for i in range(n-1,-1,-1):
            sum = 0
            for j in range(i+1, numrows):
                sum = sum + a[i,j]*x[j,0]
            x[i,0] = (b[i,0] - sum)/a[i,i]
    
    return x 

**LU FACTORIZATION**

In [75]:
def LU_factors(Amat):
    a = Amat.copy()
    
    (n, numcol) = a.shape
    
    new_order = [i for i in range(n)]
    
    if(n == numcol):
        #Factor. w/ Pivoting
        for i in range(n):
            #pivoting section
            am = abs(a[i,i])
            p = i
            for j in range(i+1, n):
                if(abs(a[j,i]) > am):
                    am = abs(a[j,i])
                    p = j
            #if the pivot index is greater than the current i index (i loops columnwise)
            #then interchange Row=pivot with Row=i
            if(p > i):
                for k in range(n):
                    temp = numpy.copy(a[i,k])
                    a[i,k] = a[p,k]
                    a[p,k] = temp
                    
                #track the swapped indices
                temp = new_order[i]
                new_order[i] = new_order[p]
                new_order[p] = temp
            
            #the pivoting is now complete
            #now begin the elimination step
            for j in range(i+1, n):
                a[j,i] = a[j,i]/a[i,i]
                for k in range(i+1, n):
                    a[j,k] = a[j,k] - a[j,i]*a[i,k]
                    
        #the pivoting is now complete so,: compute L and U
        U = numpy.matrix(numpy.zeros((n,n), dtype = numpy.float64))
        L = numpy.matrix(numpy.zeros((n,n), dtype = numpy.float64))
        
        for i in range(n):
            U[i,i] = a[i,i]
            L[i,i] = 1.0
            for j in range(n):
                if( i < j ):
                    U[i,j] = a[i,j]
                elif( i > j ):
                    L[i,j] = a[i,j]
        
                
    return L, U


LU_factors(AnMatrix(5))

(matrix([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.25      ,  1.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        , -0.        ,  1.        ,  0.        ,  0.        ],
         [ 0.        , -0.94117647,  0.48529412,  1.        ,  0.        ],
         [ 0.        , -0.        ,  0.        , -0.89180328,  1.        ]]),
 matrix([[ 4.        ,  1.        , -4.        ,  0.        ,  0.        ],
         [ 0.        , -4.25      ,  1.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  4.        ,  1.        , -4.        ],
         [ 0.        ,  0.        ,  0.        , -4.48529412,  1.94117647],
         [ 0.        ,  0.        ,  0.        ,  0.        ,  2.73114754]]))

**USING L AND U TO FORWARD AND BACK SOLVE**

In [76]:
def LU_forward_backward(L,U, bvec):
    l = L.copy()
    u = U.copy()
    b = bvec.copy()
    
    (n, numcol) = l.shape

    x = numpy.matrix(numpy.zeros((n,1), dtype = numpy.float64))
    
    if(n == numcol):
        #Solve Ly = b
        y = numpy.matrix(numpy.zeros((n,1), dtype = numpy.float64))
        y[0,0] = b[0,0]
        for i in range(1, n):
            sum = 0.0
            for j in range(0, i):
                 sum = sum + l[i,j]*y[j,0]
            y[i,0] = b[i,0] - sum
         
        #Solve Ux = y
        x[n-1, 0] = y[n-1, 0]/u[n-1,n-1]
        for i in range(n-2, -1, -1):
            sum = 0.0
            for j in range(i+1, n):
                sum = sum + u[i,j]*x[j, 0]
            x[i,0] = (y[i,0] - sum)/u[i,i]
        
    return x 

**INFINITY NORM**

In [57]:
#Input: vector
#Returns: infinity norm, i.e., maximum absolute value entry

def vecInfNorm(v):
    return numpy.max(numpy.abs(v))
        

print(vecInfNorm([3,4,7,9,100]))


100


**INFINITY MATRIX NORM**

In [80]:
#Input: matrix
#Returns: infinity matrix norm, i.e., maximum row sum

def matrixInfNorm(A):
    a = numpy.copy(A)
    a = abs(a)
    rowsums = numpy.sum(a, axis=1).tolist()
    max_s = rowsums[0]
    for elem in rowsums:
        if elem > max_s:
            max_s = elem
    return max_s
    

print(AnMatrix(6)) 

matrixInfNorm(AnMatrix(6))

[[ 1. -4.  0.  0.  0.  0.]
 [ 4.  1. -4.  0.  0.  0.]
 [ 0.  4.  1. -4.  0.  0.]
 [ 0.  0.  4.  1. -4.  0.]
 [ 0.  0.  0.  4.  1. -4.]
 [ 0.  0.  0.  0.  4.  1.]]


9.0

**EUCLIDIAN 2-NORM**

In [62]:
#Input: vector
#Returns: Euclidean 2-norm

def vecEuclidnorm(v, p):
    return numpy.power(numpy.sum(numpy.power(numpy.abs(v), 2.0)), 0.5)

  
vecEuclidnorm([2,5,7,3,5],[8,1,3,2,4]) 

10.583005244258363

**VECTOR P NORM**

In [66]:
#Input: vector, p
#Returns: vector P norm

def vecPnorm(v, p):
    return numpy.power(numpy.sum(numpy.power(numpy.abs(v), p)), 1.0/p)


vecPnorm([2,6,4,8,4],3) 

9.524406311809196

**MATRIX 2 NORM**

In [82]:
#Input: n x n matrix
#output: matrix 2 norm

def matrix2norm(Amat):

    A = numpy.matmul(Amat, numpy.transpose(Amat))
    (eigvalues, eigenvectors) = numpy.linalg.eig(A)
    mxe = max(eigvalues)
    return math.sqrt(mxe)

print(AnMatrix(7))
matrix2norm(AnMatrix(7)) 

[[ 1. -4.  0.  0.  0.  0.  0.]
 [ 4.  1. -4.  0.  0.  0.  0.]
 [ 0.  4.  1. -4.  0.  0.  0.]
 [ 0.  0.  4.  1. -4.  0.  0.]
 [ 0.  0.  0.  4.  1. -4.  0.]
 [ 0.  0.  0.  0.  4.  1. -4.]
 [ 0.  0.  0.  0.  0.  4.  1.]]


7.4583789792400275

**THE CONDITION NUMBER ESTIMATOR ALGORITHM**

In [71]:
def algorithm_79(A):
    #solve the system Ayi = yi+1, i.e., LUyi = yi+1 as a way of solving A-inverse(A^-1) yi+1 = yi
    
    a = A.copy()
    (n, numcol) = A.shape
    alpha = matrixInfNorm(A)
    (X,idx)=LU_factors(a)
    #y = numpy.random.rand(numrows, magnitude)
    y = numpy.random.rand(n, 1)
    for i in range(5):
        y = y/vecInfNorm(y)
        y = algorithm_78(L, U, y)
       
    a = A.copy()
    (n, numcol) = A.shape
    alpha = matrixInfNorm(A)
    (X,idx)=LU_factors(a)
    #y = numpy.random.rand(numrows, magnitude)
    y = numpy.random.rand(n, 1)
    for i in range(5):
        print(y)
        y = y/vecInfNorm(y)
        y = LU_forward_backward(X, idx, y)
        
        
    
    v = vecInfNorm(y)
    print("v inf")
    print(v)
    print("alpha")
    print(alpha)
    print(y)
    print(alpha * v)
